# Site settings
title: Racovita Iulia-Elena
description: Software Developer Resume

# User settings
username: Racovita Iulia-Elena
user_description: Hello! I am studying at the Faculty of Cybernetics, Statistics and Cybernetics since october 2017 and I am passionate about Java, Android and Web development.
email: racovitaiuliaelena@gmail.com
github_username:  IuliaRacovita98

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
